/// Socle unique du cycle conformité, avec un grain défini par le type d'élément.
table F_Conformite
	lineageTag: 3442adef-2166-4a69-8a03-883ff25a82ed

	column Analyse
		dataType: string
		lineageTag: 82d0f1ed-2f1b-46e6-b835-a25d17279e8f
		summarizeBy: none
		sourceColumn: analyse

	column 'Type élément'
		dataType: string
		lineageTag: 4143f03d-4b97-4239-b8cf-a39de90f50e9
		summarizeBy: none
		sourceColumn: type_element

	column Section
		dataType: string
		lineageTag: ad920447-92ba-4c33-b5c5-9d4dd140b967
		summarizeBy: none
		sourceColumn: section

	column 'Ligne reporting'
		dataType: int64
		formatString: 0
		lineageTag: 2d5e486a-55b8-4b6a-b978-0ac7ae9c9444
		summarizeBy: sum
		sourceColumn: ligne_reporting

		annotation SummarizationSetBy = Automatic

	column Rubrique
		dataType: string
		lineageTag: 073c9a8f-0542-441e-b545-91e9843217db
		summarizeBy: none
		sourceColumn: rubrique

	column 'Date début'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 69ff7334-f9c2-4bba-a9e6-5cfff20e1df6
		summarizeBy: none
		sourceColumn: date_debut

		annotation UnderlyingDateTimeDataType = Date

	column 'Date fin'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c1b48408-b985-4761-b71c-7c823e50de2f
		summarizeBy: none
		sourceColumn: date_fin

		annotation UnderlyingDateTimeDataType = Date

	column 'Date événement'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f5c8e1d-7cf3-4b5c-b165-e2774b4a87c1
		summarizeBy: none
		sourceColumn: date_evenement

		annotation UnderlyingDateTimeDataType = Date

	column 'Code client'
		dataType: string
		lineageTag: b52dfffd-c665-4411-a69b-de94237ddaf3
		summarizeBy: none
		sourceColumn: code_client

	column 'Nom client'
		dataType: string
		lineageTag: 34701d10-0ac2-4b96-aa24-49fbf5975657
		summarizeBy: none
		sourceColumn: nom_client

	column 'Numéro compte'
		dataType: string
		lineageTag: 4eb25f35-18e8-40af-946a-211a1097bddd
		summarizeBy: none
		sourceColumn: numero_compte

	column 'Numéro alerte'
		dataType: string
		lineageTag: 7a5e5a3f-ecc0-4916-8e9f-69552efecd90
		summarizeBy: none
		sourceColumn: numero_alerte

	column 'Référence interne'
		dataType: string
		lineageTag: 46c29db2-20dc-4103-a291-7b371d67cdda
		summarizeBy: none
		sourceColumn: reference_interne

	column 'Référence externe'
		dataType: string
		lineageTag: 6538ac6f-18c8-435c-a735-21e962d9ea28
		summarizeBy: none
		sourceColumn: reference_externe

	column 'Numéro opération'
		dataType: string
		lineageTag: 120229de-6c85-49df-959f-1a7d58027a2b
		summarizeBy: none
		sourceColumn: numero_operation

	column 'Type opération'
		dataType: string
		lineageTag: b4632435-32e1-4e37-ba77-ab7bb68fed20
		summarizeBy: none
		sourceColumn: type_operation

	column Description
		dataType: string
		lineageTag: 9ae8ce35-1cd6-4637-98a0-c271269ea78b
		summarizeBy: none
		sourceColumn: description

	column État
		dataType: string
		lineageTag: 40ba7039-0525-47c9-ba06-1fe4cd8e6469
		summarizeBy: none
		sourceColumn: etat

	column 'Statut revue'
		dataType: string
		lineageTag: 27970de4-1878-4c4d-ba00-d412c6c0218e
		summarizeBy: none
		sourceColumn: statut_revue

	column 'Statut couverture'
		dataType: string
		lineageTag: d1f4e0eb-1bd4-4bcd-b9f3-3c30d91c0664
		summarizeBy: none
		sourceColumn: statut_couverture

	column 'Origine déclaration'
		dataType: string
		lineageTag: 6b7b844c-62cb-4eb5-bbed-e61579239a7f
		summarizeBy: none
		sourceColumn: origine_declaration

	column Devise
		dataType: string
		lineageTag: ac0820ee-7504-457b-8628-5c118205c66e
		summarizeBy: none
		sourceColumn: devise

	column Montant
		dataType: double
		lineageTag: a10a6234-f0d5-4a6a-b762-d469928bdd31
		summarizeBy: none
		sourceColumn: montant

	column Volume
		dataType: double
		lineageTag: 915f585a-f31c-45e8-a4d4-9bfb065a96c1
		summarizeBy: none
		sourceColumn: volume

	column Nombre
		dataType: double
		lineageTag: 74cb4d50-1506-4b56-b5a1-0c830855b339
		summarizeBy: sum
		sourceColumn: nombre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Niveau risque'
		dataType: string
		lineageTag: 2b2a99b6-898b-423a-8103-f60d36b7a309
		summarizeBy: none
		sourceColumn: niveau_risque

	column 'Profil risque'
		dataType: string
		lineageTag: 0d84e8b0-02bf-4f3f-a6c7-cd18ccccab01
		summarizeBy: none
		sourceColumn: profil_risque

	column Sévérité
		dataType: string
		lineageTag: 01a9223f-7ec9-43d5-bf98-a3d796aae673
		summarizeBy: none
		sourceColumn: severite

	column 'Action recommandée'
		dataType: string
		lineageTag: 71b9d5c9-7d97-4120-838e-af9cf1b6151b
		summarizeBy: none
		sourceColumn: action_recommandee

	column 'Origine donnée'
		dataType: string
		lineageTag: a7f013eb-2e5f-47a6-bef2-2d4bc4ee993c
		summarizeBy: none
		sourceColumn: origine_donnee

	column Commentaire
		dataType: string
		lineageTag: 55b30460-e732-4070-9c84-602f0956699c
		summarizeBy: none
		sourceColumn: commentaire

	column 'Point service'
		dataType: string
		lineageTag: 2ee96343-1674-42af-a1f5-8783f014c0d4
		summarizeBy: none
		sourceColumn: point_service

	column Motif
		dataType: string
		lineageTag: d3e61811-7aae-46bb-a080-24ff79b7b8f3
		summarizeBy: none
		sourceColumn: motif

	column Indicateurs
		dataType: string
		lineageTag: d1b1635b-c0e6-47a6-84de-5987d38dc95e
		summarizeBy: none
		sourceColumn: indicateurs

	partition F_Conformite = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_conformite"]}[Data],
					FiltrePeriode = Table.SelectRows(TableSource, each [date_debut] = pDateDebut and [date_fin] = pDateFin),
					Resultat = Table.SelectColumns(FiltrePeriode, {"analyse", "type_element", "section", "ligne_reporting", "rubrique", "date_debut", "date_fin", "date_evenement", "code_client", "nom_client", "numero_compte", "numero_alerte", "reference_interne", "reference_externe", "numero_operation", "type_operation", "description", "etat", "statut_revue", "statut_couverture", "origine_declaration", "devise", "montant", "volume", "nombre", "niveau_risque", "profil_risque", "severite", "action_recommandee", "origine_donnee", "commentaire", "point_service", "motif", "indicateurs"}, MissingField.UseNull)
				in
					Resultat

	annotation RequetePerfectVision = 156

	annotation SourceLocale = BB_VISION_REPORTING.rpt navigation

