/// Photographie du portefeuille crédit, du PAR et des provisions à la date de situation.
table F_Credit_Portefeuille
	lineageTag: 24143331-be3c-4dbf-8854-6104dcaeac20

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9c0f1d6b-0e52-49db-b6ae-cf4275f87649
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: f81189f7-2254-4a35-891b-04215213fb92
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 9f2f38b6-1a93-4bfc-abdb-1a1e2c6fac7f
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: 83624845-09e5-4014-8080-421a501c9695
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 0fefc36e-6f26-4b6d-be0c-98ff2e5510c0
		summarizeBy: none
		sourceColumn: code_devise

	column 'Prêts actifs'
		dataType: int64
		lineageTag: ea3e7e19-bf7a-4a0b-bb48-baeaa566a7c3
		summarizeBy: none
		sourceColumn: nb_prets_actifs

	column Encours
		dataType: double
		lineageTag: fa948892-f7ef-402d-8e19-bc7903fea92b
		summarizeBy: none
		sourceColumn: encours_total

	column 'PAR 1+'
		dataType: double
		lineageTag: adfe51f4-ff64-448d-8ded-ee6603432754
		summarizeBy: none
		sourceColumn: par_1_plus

	column 'PAR 30+'
		dataType: double
		lineageTag: c9bd45bd-83ce-44a7-9105-1a1196557419
		summarizeBy: none
		sourceColumn: par_30_plus

	column 'PAR 90+'
		dataType: double
		lineageTag: fa68c506-41aa-4426-b14f-e589d7a7c95d
		summarizeBy: none
		sourceColumn: par_90_plus

	column 'PAR 180+'
		dataType: double
		lineageTag: 46a35666-4444-45bf-b6b1-f2facb12eb45
		summarizeBy: none
		sourceColumn: par_180_plus

	column Provision
		dataType: double
		lineageTag: 00048690-1b6a-4624-8cef-eb023cb75fb6
		summarizeBy: none
		sourceColumn: provision_total

	column 'Taux PAR 1+'
		dataType: double
		lineageTag: 916095aa-3cd3-4ad6-8c7e-5efaf6a1af8a
		summarizeBy: none
		sourceColumn: par_1_pct

	column 'Taux PAR 30+'
		dataType: double
		lineageTag: ad7c62dc-0b65-4451-b92f-86b3fe90e353
		summarizeBy: none
		sourceColumn: par_30_pct

	column 'Taux PAR 90+'
		dataType: double
		lineageTag: ec6b0864-f223-4482-8aad-4a026a64ef11
		summarizeBy: none
		sourceColumn: par_90_pct

	partition F_Credit_Portefeuille = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_portefeuille"]}[Data],
					FiltreSituation = Table.SelectRows(TableSource, each [date_situation] = pDateFin),
					ColonnesModele = Table.SelectColumns(FiltreSituation, {
						"date_situation", "code_agence", "agence", "produit_credit", "devise",
						"prets_actifs", "encours", "par_1_plus", "par_30_plus", "par_90_plus",
						"par_180_plus", "provision", "taux_par_1_plus", "taux_par_30_plus", "taux_par_90_plus"
					}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"prets_actifs", "nb_prets_actifs"},
						{"encours", "encours_total"},
						{"provision", "provision_total"},
						{"taux_par_1_plus", "par_1_pct"},
						{"taux_par_30_plus", "par_30_pct"},
						{"taux_par_90_plus", "par_90_pct"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 97

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_portefeuille

