/// Durée et nombre d'échéances restantes des prêts actifs.
table F_Credit_Duree
	lineageTag: 808fae0d-afbb-4b32-a42b-9d89be5c77ad

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc82ce7b-0718-4aad-b20c-e18037b05c3b
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: c884a8a1-44f3-4a3e-aa40-698c8080d07e
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: a3f53ab5-52d8-47f3-a495-4411fd9168ee
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: e72ccfc4-0c34-4162-8611-187a4a112896
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 80ea5bfc-09a6-4e21-945f-7c22e1e74295
		summarizeBy: none
		sourceColumn: code_devise

	column 'Numéro prêt'
		dataType: string
		lineageTag: 70fa0e87-8fb0-455e-96ab-17b1e2048a5a
		summarizeBy: none
		sourceColumn: numero_pret

	column 'Code client'
		dataType: string
		lineageTag: b62d9fca-3e67-4f80-9b92-6e5d29957770
		summarizeBy: none
		sourceColumn: code_client

	column 'Nom client'
		dataType: string
		lineageTag: 8631a151-8f37-49db-9f48-e6f5250129e0
		summarizeBy: none
		sourceColumn: nom_client

	column 'Date effet'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9baed82f-0efe-4f6f-9b43-514e7b2a183c
		summarizeBy: none
		sourceColumn: date_effet

		annotation UnderlyingDateTimeDataType = Date

	column 'Date fin échéance'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d3efdcbf-d40f-421a-92fc-b31e139feef7
		summarizeBy: none
		sourceColumn: date_fin_echeance

		annotation UnderlyingDateTimeDataType = Date

	column 'Montant initial'
		dataType: double
		lineageTag: 5a4866a2-bf3b-41b1-8970-0a7582a9b696
		summarizeBy: none
		sourceColumn: montant_initial

	column 'Échéances totales'
		dataType: int64
		lineageTag: 0faa4019-2c4a-43f9-80d6-957662e09d06
		summarizeBy: none
		sourceColumn: nb_echeances_total

	column 'Échéances restantes'
		dataType: int64
		lineageTag: 537300c4-96ab-49bf-add8-4b02b30bf041
		summarizeBy: none
		sourceColumn: nb_echeances_restantes

	column 'Durée théorique mois'
		dataType: int64
		lineageTag: 0fde3a6c-a579-40a9-a949-267df2bba565
		summarizeBy: none
		sourceColumn: duree_theorique_mois

	column 'Tranche échéances restantes'
		dataType: string
		lineageTag: dfee1474-2624-4aee-9dfb-89703e0c2fdf
		summarizeBy: none
		sourceColumn: tranche_echeances_restantes

	column 'Tranche total échéances'
		dataType: string
		lineageTag: d0958cf5-85f2-4847-8bd8-89d3da4b11c4
		summarizeBy: none
		sourceColumn: tranche_total_echeances

	column prenoms_client
		dataType: string
		lineageTag: f5a949d9-6327-45c0-bbe8-04d27ff9f17a
		summarizeBy: none
		sourceColumn: prenoms_client

		annotation SummarizationSetBy = Automatic

	partition F_Credit_Duree = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_duree"]}[Data],
					DateSituation = pDateFin,
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] = DateSituation),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"date_situation", "code_agence", "agence", "produit_credit", "devise", "numero_pret", "code_client", "nom_client", "date_effet", "date_fin_echeance", "montant_initial", "echeances_totales", "echeances_restantes", "duree_theorique_mois", "tranche_echeances_restantes", "tranche_total_echeances", "prenoms_client"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"echeances_totales", "nb_echeances_total"},
						{"echeances_restantes", "nb_echeances_restantes"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 108

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_duree

