/// Couverture des arriérés et du principal par épargne, cautions et garanties.
table F_Credit_Couverture
	lineageTag: 9144252c-823b-4ab5-8fec-7d976873cdc1

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 100db3d3-c89a-437f-870f-f79a97b29e83
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: a2b1eb3d-0a32-44d0-b349-ce9de0f253f8
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 7b028178-7786-428a-84c9-ebce813245a6
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: 252f6bdc-d474-4ad4-abe8-c7aa174ad7bf
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 713091dc-4d85-4c5c-8fcf-d09f3dfbb64b
		summarizeBy: none
		sourceColumn: code_devise

	column 'Code client'
		dataType: string
		lineageTag: 915f9fa8-6334-4765-8293-90f063b0cb80
		summarizeBy: none
		sourceColumn: code_client

	column 'Nom client'
		dataType: string
		lineageTag: f00114ba-d23f-4cb9-b449-038a3eb604c0
		summarizeBy: none
		sourceColumn: nom_client

	column 'Numéro prêt'
		dataType: string
		lineageTag: 99157104-4aba-442b-a78e-b28df2fb94f0
		summarizeBy: none
		sourceColumn: numero_pret

	column 'Montant initial'
		dataType: double
		lineageTag: 9a93809b-af2f-484d-a75a-4d111a9da2ec
		summarizeBy: none
		sourceColumn: montant_initial

	column Encours
		dataType: double
		lineageTag: b4c43790-bd24-4fa9-bd51-84f2b28026d6
		summarizeBy: none
		sourceColumn: mtt_encours

	column Arriéré
		dataType: double
		lineageTag: 6b024daf-0e41-4bdf-8af2-afeba24f8890
		summarizeBy: none
		sourceColumn: montant_arriere

	column 'Épargne client'
		dataType: double
		lineageTag: af756f0f-a50c-446c-9377-5cd4be6a24a6
		summarizeBy: none
		sourceColumn: solde_epargne_client

	column Caution
		dataType: double
		lineageTag: 20f210fa-dffb-4d29-ade9-f854d86d058a
		summarizeBy: none
		sourceColumn: solde_caution

	column Garantie
		dataType: double
		lineageTag: 4c995f43-f85b-41e5-b3a7-18326cb28b68
		summarizeBy: none
		sourceColumn: valeur_garantie

	column 'Arriéré couvert'
		dataType: double
		lineageTag: b8d9459e-c72d-41f2-88cf-0bd82e6c3175
		summarizeBy: none
		sourceColumn: arriere_couvert_par_epargne

	column 'Principal couvert'
		dataType: double
		lineageTag: dce8ccdc-2506-485e-93b9-3ec932a82bb4
		summarizeBy: none
		sourceColumn: principal_couvert

	column 'Exposition nette'
		dataType: double
		lineageTag: d515371e-a771-41f6-a817-f14490d332b5
		summarizeBy: none
		sourceColumn: exposition_nette_non_couverte

	column prenoms_client
		dataType: string
		lineageTag: 79e99fcf-8833-4f04-ac0e-33144990890e
		summarizeBy: none
		sourceColumn: prenoms_client

		annotation SummarizationSetBy = Automatic

	partition F_Credit_Couverture = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_couverture"]}[Data],
					DateSituation = pDateFin,
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] = DateSituation),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"date_situation", "code_agence", "agence", "produit_credit", "devise", "code_client", "nom_client", "numero_pret", "montant_initial", "encours", "arriere", "epargne_client", "caution", "garantie", "arriere_couvert", "principal_couvert", "exposition_nette", "prenoms_client"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"encours", "mtt_encours"},
						{"arriere", "montant_arriere"},
						{"epargne_client", "solde_epargne_client"},
						{"caution", "solde_caution"},
						{"garantie", "valeur_garantie"},
						{"arriere_couvert", "arriere_couvert_par_epargne"},
						{"exposition_nette", "exposition_nette_non_couverte"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 106

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_couverture

