/// Décaissements de crédits par mois, agence, produit, devise et type de client.
table F_Credit_Decaissements
	lineageTag: 01439452-12f7-4a85-b62a-950e43dd2766

	column 'Mois décaissement'
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc2eaff4-2c63-4d5b-a83f-fa7a07e69ba8
		summarizeBy: none
		sourceColumn: mois_decaissement

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: aed0fb62-05d2-43fa-b3c9-11859bf01837
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 7ef06135-a224-46e7-85c8-c905eb365592
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: 29892b48-a8ac-48be-b394-9f39ab403cff
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 1c10981e-4832-41cc-95c8-68f0a8dbc3f6
		summarizeBy: none
		sourceColumn: code_devise

	column 'Code type client'
		dataType: int64
		lineageTag: 801fc0f8-9831-425a-ba0c-7fcd8064b722
		summarizeBy: none
		sourceColumn: code_type_client

	column 'Type client'
		dataType: string
		lineageTag: fda0ad3c-144b-4099-a702-d67cbc51de07
		summarizeBy: none
		sourceColumn: type_client

	column 'Prêts décaissés'
		dataType: int64
		lineageTag: 927318e2-8426-4f9f-bfd8-080128695501
		summarizeBy: none
		sourceColumn: nb_prets_decaisse

	column 'Clients décaissés'
		dataType: int64
		lineageTag: a9757fb3-8a74-4e5c-97b4-dfb7878f03ca
		summarizeBy: none
		sourceColumn: nb_clients_decaisse

	column 'Montant décaissé'
		dataType: double
		lineageTag: d7354267-ec66-42c7-b575-3be18371ba39
		summarizeBy: none
		sourceColumn: montant_decaisse

	column 'Montant moyen prêt'
		dataType: double
		lineageTag: b959c858-ab4f-4859-8a91-cb7d42b413a1
		summarizeBy: none
		sourceColumn: montant_moyen_pret

	partition F_Credit_Decaissements = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_decaissements"]}[Data],
					MoisDebut = Date.StartOfMonth(pDateDebut),
					MoisFin = Date.StartOfMonth(pDateFin),
					FiltrePeriode = Table.SelectRows(TableSource, each [mois_decaissement] >= MoisDebut and [mois_decaissement] <= MoisFin),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {
						"mois_decaissement", "code_agence", "agence", "produit_credit", "devise",
						"code_type_client", "type_client", "prets_decaisses", "clients_decaisses",
						"montant_decaisse", "montant_moyen_pret"
					}),
					TypesModele = Table.TransformColumnTypes(ColonnesModele, {{"code_type_client", Int64.Type}}),
					Resultat = Table.RenameColumns(TypesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"prets_decaisses", "nb_prets_decaisse"},
						{"clients_decaisses", "nb_clients_decaisse"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 99

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_decaissements

