/// Principaux encours de crédit par client et prêt à la date de situation.
table F_Credit_Top_Encours
	lineageTag: ece7cddf-672e-4738-97aa-add9121cec63

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 25df6a9a-afe9-4457-9441-83dbb61a6c90
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: e93fcc62-bb3e-4729-a6f2-e1860c3e7818
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: f77f0a28-a92c-4add-890d-14fedc75775d
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: 01b205e0-eeff-4462-ac58-43420a644caa
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: bab524ea-9ddf-4a8a-88df-fe84b1703fea
		summarizeBy: none
		sourceColumn: code_devise

	column 'Code client'
		dataType: string
		lineageTag: a9b77ccd-0141-415d-afc0-ef62d2655ed6
		summarizeBy: none
		sourceColumn: code_client

	column 'Nom client'
		dataType: string
		lineageTag: 81e01acd-9afe-4227-b467-67ddbe857dc6
		summarizeBy: none
		sourceColumn: nom_client

	column 'Numéro prêt'
		dataType: string
		lineageTag: d31b08d2-0c06-453d-af60-4038b437e481
		summarizeBy: none
		sourceColumn: numero_pret

	column 'Montant initial'
		dataType: double
		lineageTag: d7b5a67f-dd70-44a4-806b-2792a3414fa4
		summarizeBy: none
		sourceColumn: montant_initial

	column Encours
		dataType: double
		lineageTag: 33c1450e-59e7-483e-86bf-1f369915a7df
		summarizeBy: none
		sourceColumn: mtt_encours

	column num_manuel
		dataType: string
		lineageTag: d2288221-5333-4edf-b54f-af54b440caf1
		summarizeBy: none
		sourceColumn: num_manuel

		annotation SummarizationSetBy = Automatic

	column prenoms_client
		dataType: string
		lineageTag: 5d33e683-0d54-42ff-ab0b-f0e66e033635
		summarizeBy: none
		sourceColumn: prenoms_client

		annotation SummarizationSetBy = Automatic

	column code_type_client
		dataType: string
		lineageTag: 87bd7d6c-513b-429f-9dda-6c8c79038a70
		summarizeBy: none
		sourceColumn: code_type_client

		annotation SummarizationSetBy = Automatic

	column type_client
		dataType: string
		lineageTag: 723dfc6f-7818-4261-9acd-6c20f1004755
		summarizeBy: none
		sourceColumn: type_client

		annotation SummarizationSetBy = Automatic

	column date_effet
		dataType: dateTime
		formatString: Long Date
		lineageTag: 326e943f-3111-4cde-9475-9b65034b8090
		summarizeBy: none
		sourceColumn: date_effet

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_decaissement
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5312b2d3-fff2-45ae-a054-e0d61311eb6e
		summarizeBy: none
		sourceColumn: date_decaissement

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition F_Credit_Top_Encours = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_top_encours"]}[Data],
					DateSituation = pDateFin,
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] = DateSituation),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"date_situation", "code_agence", "agence", "produit_credit", "devise", "code_client", "nom_client", "numero_pret", "montant_initial", "encours", "num_manuel", "prenoms_client", "code_type_client", "type_client", "date_effet", "date_decaissement"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"encours", "mtt_encours"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 98

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_top_encours

