/// Qualité des cohortes de décaissement et PAR par âge de cohorte.
table F_Credit_Vintage
	lineageTag: b37d217f-418e-4091-b70d-d326140efefc

	column 'Cohorte décaissement'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45eee93d-a8bd-4c33-bd7a-46be625c10e0
		summarizeBy: none
		sourceColumn: cohorte_decaissement

		annotation UnderlyingDateTimeDataType = Date

	column 'Âge cohorte mois'
		dataType: int64
		lineageTag: e2683da6-10bb-42e2-98d4-8b1e6196a24a
		summarizeBy: none
		sourceColumn: age_cohorte_mois

	column 'Code agence'
		dataType: string
		lineageTag: 6829c419-c284-466a-b422-a9c14cf3fc70
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 861d69d4-1215-4010-a9cd-434106081ac1
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: a3dd6df3-ea1f-42be-8068-412a9c439c52
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 3c8e0abf-b243-487c-892c-04ade9344d2d
		summarizeBy: none
		sourceColumn: code_devise

	column 'Prêts décaissés'
		dataType: int64
		lineageTag: 32d319ea-dd9b-4a03-9232-437864dc617a
		summarizeBy: none
		sourceColumn: nb_prets_decaisse

	column 'Montant initial cohorte'
		dataType: double
		lineageTag: d52df373-006f-45c4-8859-6b9c76178cf4
		summarizeBy: none
		sourceColumn: montant_initial_cohorte

	column 'Encours restant'
		dataType: double
		lineageTag: 4d338065-af65-4564-b599-1435dee4f7b2
		summarizeBy: none
		sourceColumn: encours_restant

	column 'PAR 30+'
		dataType: double
		lineageTag: 0d1edaec-d0f7-49f9-9cbd-1fcc89c784f2
		summarizeBy: none
		sourceColumn: par_30_plus

	column 'PAR 90+'
		dataType: double
		lineageTag: 122ee305-df22-4ac6-a6a0-9cdfdfda6b6b
		summarizeBy: none
		sourceColumn: par_90_plus

	column 'PAR 30 sur initial'
		dataType: double
		lineageTag: 764d1a65-ba79-451c-9ea3-9dbffb4c1911
		summarizeBy: none
		sourceColumn: par_30_sur_initial_pct

	column 'PAR 90 sur initial'
		dataType: double
		lineageTag: 3b8eb4d1-47a1-4f19-9889-6aee25e8aa86
		summarizeBy: none
		sourceColumn: par_90_sur_initial_pct

	partition F_Credit_Vintage = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_vintage"]}[Data],
					MoisDebut = Date.StartOfMonth(pDateDebut),
					MoisFin = Date.StartOfMonth(pDateFin),
					FiltrePeriode = Table.SelectRows(TableSource, each [cohorte_decaissement] >= MoisDebut and [cohorte_decaissement] <= MoisFin),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"cohorte_decaissement", "age_cohorte_mois", "code_agence", "agence", "produit_credit", "devise", "prets_decaisses", "montant_initial_cohorte", "encours_restant", "par_30_plus", "par_90_plus", "par_30_sur_initial", "par_90_sur_initial"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"prets_decaisses", "nb_prets_decaisse"},
						{"par_30_sur_initial", "par_30_sur_initial_pct"},
						{"par_90_sur_initial", "par_90_sur_initial_pct"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 102

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_vintage

