/// Tendance mensuelle de l'encours et du portefeuille à risque.
table F_Credit_Tendance_PAR
	lineageTag: 2bb8f97e-41d8-46b2-9ca8-8b24a0a86596

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd11f3b2-9d92-46c3-99ce-70dbd69c5891
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: ef4c3e50-79d0-4c0f-bd3f-5ee60ed1d1d8
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 61b5735d-ec1d-43ee-94bd-748b1f969054
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: b297ee03-b4cf-4f29-b9d9-2b121cdf83ee
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: af71146c-d7ea-443e-9b52-142a8fe4160f
		summarizeBy: none
		sourceColumn: code_devise

	column 'Prêts actifs'
		dataType: int64
		lineageTag: c26d333e-a947-4356-809d-60eed617eadf
		summarizeBy: none
		sourceColumn: nb_prets_actifs

	column Encours
		dataType: double
		lineageTag: 30355fc0-7f7e-4f59-88e4-7f8e932f9155
		summarizeBy: none
		sourceColumn: encours_total

	column 'PAR 1+'
		dataType: double
		lineageTag: 56209ba3-ce66-453a-9a3b-4f7259f80bb0
		summarizeBy: none
		sourceColumn: par_1_plus

	column 'PAR 30+'
		dataType: double
		lineageTag: fb08d7d2-87ad-4484-9fd2-7c54e7d21c8e
		summarizeBy: none
		sourceColumn: par_30_plus

	column 'PAR 90+'
		dataType: double
		lineageTag: acc0bf49-e5a7-4066-93e5-e0b1fc6145b6
		summarizeBy: none
		sourceColumn: par_90_plus

	column 'Taux PAR 30+'
		dataType: double
		lineageTag: cde0356c-87f3-40ed-aa1d-726252d59529
		summarizeBy: none
		sourceColumn: par_30_pct

	partition F_Credit_Tendance_PAR = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_tendance_par"]}[Data],
					DateSituation = pDateFin,
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] = DateSituation),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"date_situation", "code_agence", "agence", "produit_credit", "devise", "prets_actifs", "encours", "par_1_plus", "par_30_plus", "par_90_plus", "taux_par_30_plus"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"prets_actifs", "nb_prets_actifs"},
						{"encours", "encours_total"},
						{"taux_par_30_plus", "par_30_pct"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 109

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_tendance_par

