/// Rétention et renouvellement des clients crédit arrivés à échéance.
table F_Credit_Retention
	lineageTag: e9764ef2-503d-4e6e-b133-afd00f733b0e

	column 'Mois solde'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d5895710-01d2-4c3c-90e0-f0ced9bf316a
		summarizeBy: none
		sourceColumn: mois_solde

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: 5ef3548e-778d-46aa-a782-84841726fcd8
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 2b771cc2-1d50-412d-8e23-42673196fd66
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: d295b774-1522-4d8e-8506-1e610e769d94
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 81866b56-53c7-430d-995a-e4c14e5cd773
		summarizeBy: none
		sourceColumn: code_devise

	column 'Clients arrivés échéance'
		dataType: int64
		lineageTag: f4885ce1-e6fb-4944-85b4-ed2d150b5cdd
		summarizeBy: none
		sourceColumn: nb_clients_arrives_echeance

	column 'Prêts soldés'
		dataType: int64
		lineageTag: f219a19a-a69d-4862-93a8-5f3f201102ff
		summarizeBy: none
		sourceColumn: nb_prets_soldes

	column 'Montant prêts soldés'
		dataType: double
		lineageTag: 0f6f2d58-439e-4bd7-9365-4d9324c5cc24
		summarizeBy: none
		sourceColumn: montant_prets_soldes

	column 'Clients renouvelés'
		dataType: int64
		lineageTag: 144e9add-4921-4d88-9be8-d12671900c53
		summarizeBy: none
		sourceColumn: nb_clients_renouveles

	column 'Clients renouvelés 90j'
		dataType: int64
		lineageTag: 29aa44df-98d6-4b78-9d0c-5c34d71019fd
		summarizeBy: none
		sourceColumn: nb_clients_renouveles_90j

	column Rétention
		dataType: double
		lineageTag: a6c3bea6-aa5e-4c70-9fa8-e703bf8071a3
		summarizeBy: none
		sourceColumn: retention_pct

	column 'Rétention 90j'
		dataType: double
		lineageTag: f991ce03-f2ee-41c6-9774-d44a28e513ac
		summarizeBy: none
		sourceColumn: retention_90j_pct

	column 'Délai moyen renouvellement'
		dataType: double
		lineageTag: 1fb1ff84-3443-4dd5-b415-8ed10ee133d6
		summarizeBy: none
		sourceColumn: delai_moyen_renouvellement_jours

	partition F_Credit_Retention = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_retention"]}[Data],
					MoisDebut = Date.StartOfMonth(pDateDebut),
					MoisFin = Date.StartOfMonth(pDateFin),
					FiltrePeriode = Table.SelectRows(TableSource, each [mois_solde] >= MoisDebut and [mois_solde] <= MoisFin),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"mois_solde", "code_agence", "agence", "produit_credit", "devise", "clients_arrives_echeance", "prets_soldes", "montant_prets_soldes", "clients_renouveles", "clients_renouveles_90j", "retention", "retention_90j", "delai_moyen_renouvellement"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"clients_arrives_echeance", "nb_clients_arrives_echeance"},
						{"prets_soldes", "nb_prets_soldes"},
						{"clients_renouveles", "nb_clients_renouveles"},
						{"clients_renouveles_90j", "nb_clients_renouveles_90j"},
						{"retention", "retention_pct"},
						{"retention_90j", "retention_90j_pct"},
						{"delai_moyen_renouvellement", "delai_moyen_renouvellement_jours"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 101

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_retention

