/// Provisions de crédit détaillées sur les trois derniers mois.
table F_Credit_Provisions_Detail
	lineageTag: ae3e599e-143f-42af-a097-2284c0639a54

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e76e998-28b3-446f-acaa-f91bc154f25d
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: 37b07dd4-b4ce-4060-a35f-1451e1e1b730
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: b0edd728-4b8d-43e0-a623-7db6bda2f25f
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: d173478d-521e-46a4-901e-b7bebe745104
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: fe417538-b0b4-4024-a618-ef3b989e33a0
		summarizeBy: none
		sourceColumn: code_devise

	column 'Code client'
		dataType: string
		lineageTag: 3a691444-43ea-4ba8-a25a-4325a933d2f9
		summarizeBy: none
		sourceColumn: code_client

	column 'Nom client'
		dataType: string
		lineageTag: 42b63d93-cd2d-41a4-9342-b028d166daa2
		summarizeBy: none
		sourceColumn: nom_client

	column 'Numéro prêt'
		dataType: string
		lineageTag: b9ff36f5-bad6-4675-8dae-a1c7ca599ec4
		summarizeBy: none
		sourceColumn: numero_pret

	column 'Montant initial'
		dataType: double
		lineageTag: 747b9005-f8d2-4c7f-87d0-502b4e778489
		summarizeBy: none
		sourceColumn: montant_initial

	column 'Tranche montant'
		dataType: string
		lineageTag: 1ca94b5c-0bcd-43d7-a3e9-edf41153a02e
		summarizeBy: none
		sourceColumn: tranche_montant_initial

	column Provision
		dataType: double
		lineageTag: 10fdbe56-887a-4dd4-9432-d51d792b0282
		summarizeBy: none
		sourceColumn: mtt_provision

	column prenoms_client
		dataType: string
		lineageTag: 9afa39ef-517f-404c-b5d5-c2428147220c
		summarizeBy: none
		sourceColumn: prenoms_client

		annotation SummarizationSetBy = Automatic

	partition F_Credit_Provisions_Detail = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_provisions_detail"]}[Data],
					DateSituationDebut = Date.EndOfMonth(Date.AddMonths(pDateFin, -2)),
					DateSituationFin = Date.EndOfMonth(pDateFin),
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] >= DateSituationDebut and [date_situation] <= DateSituationFin),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"date_situation", "code_agence", "agence", "produit_credit", "devise", "code_client", "nom_client", "numero_pret", "montant_initial", "tranche_montant", "provision", "prenoms_client"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"tranche_montant", "tranche_montant_initial"},
						{"provision", "mtt_provision"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 107

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_provisions_detail

