/// Portefeuille et PAR par tranche de montant initial.
table F_Credit_Tranches
	lineageTag: 156ca107-d0cd-4dba-8b7f-8d2e10847143

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d446aa2b-72eb-43af-8b69-979b4d7d240d
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: 2c5a364c-8a39-4f76-86ab-027b0f0b4ec2
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: a6a9dd8c-2053-4c85-b4fb-24209b108352
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: a9e3bdde-e573-4a16-a654-1b6a8ead2965
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 896f2ae0-314d-45db-b1c0-9b346f74e31a
		summarizeBy: none
		sourceColumn: code_devise

	column 'Tranche montant'
		dataType: string
		lineageTag: 8b89898d-6e39-4e0e-bd1a-2e870f611932
		summarizeBy: none
		sourceColumn: tranche_montant_initial

	column Clients
		dataType: int64
		lineageTag: 476cfc7f-cfb1-4345-9900-766de8a01337
		summarizeBy: none
		sourceColumn: nb_clients

	column Prêts
		dataType: int64
		lineageTag: 6c555188-2417-434c-9e05-befe803466b7
		summarizeBy: none
		sourceColumn: nb_prets

	column 'Montant initial'
		dataType: double
		lineageTag: 6cbb9725-961b-4c59-9c98-5e24a8f405bf
		summarizeBy: none
		sourceColumn: montant_initial_total

	column Encours
		dataType: double
		lineageTag: 5349cb42-fa4f-467b-9b2d-7964b937df66
		summarizeBy: none
		sourceColumn: encours_total

	column 'PAR 1+'
		dataType: double
		lineageTag: 0c8bb204-1b5a-44e8-b8a5-a139803b8cc7
		summarizeBy: none
		sourceColumn: par_1_plus

	column 'PAR 30+'
		dataType: double
		lineageTag: 498f087c-ff17-4723-8512-e74a27276458
		summarizeBy: none
		sourceColumn: par_30_plus

	column 'PAR 90+'
		dataType: double
		lineageTag: 8bf5c65e-9961-4aaa-9fdd-463ec79e3d98
		summarizeBy: none
		sourceColumn: par_90_plus

	column 'Taux PAR 1+'
		dataType: double
		lineageTag: a16c5596-120e-40c9-8047-cb06a58e7fb8
		summarizeBy: none
		sourceColumn: par_1_pct

	column 'Taux PAR 30+'
		dataType: double
		lineageTag: fbe428f8-8d17-4ca6-be88-532c2129aca8
		summarizeBy: none
		sourceColumn: par_30_pct

	column 'Taux PAR 90+'
		dataType: double
		lineageTag: 26869c17-c0ed-4d18-b586-4fd941803ec5
		summarizeBy: none
		sourceColumn: par_90_pct

	partition F_Credit_Tranches = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_tranches"]}[Data],
					DateSituation = pDateFin,
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] = DateSituation),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"date_situation", "code_agence", "agence", "produit_credit", "devise", "tranche_montant", "clients", "prets", "montant_initial", "encours", "par_1_plus", "par_30_plus", "par_90_plus", "taux_par_1_plus", "taux_par_30_plus", "taux_par_90_plus"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"tranche_montant", "tranche_montant_initial"},
						{"clients", "nb_clients"},
						{"prets", "nb_prets"},
						{"montant_initial", "montant_initial_total"},
						{"encours", "encours_total"},
						{"taux_par_1_plus", "par_1_pct"},
						{"taux_par_30_plus", "par_30_pct"},
						{"taux_par_90_plus", "par_90_pct"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 104

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_tranches

