/// Détail du portefeuille à risque par prêt et client à la date de situation.
table F_Credit_PAR_Detail
	lineageTag: 6dd6e51d-d18a-414f-9002-045b0c0e4450

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4e65685-8e9a-4248-9a9c-665102c1457e
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: 74cfbf04-508b-4e6d-9c87-623c8b5837d7
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 3131620d-1cce-4b8f-a7ee-29fcea34749c
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: c1dce083-47f9-4a39-90e6-e6493ac6c0bc
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 0fbd29bd-56d6-45ce-bd68-6345ec211a3b
		summarizeBy: none
		sourceColumn: code_devise

	column 'Code client'
		dataType: string
		lineageTag: 6aa81ded-6fdf-4e9a-8f90-f79794794a2e
		summarizeBy: none
		sourceColumn: code_client

	column 'Nom client'
		dataType: string
		lineageTag: e53b592a-54d1-4d70-aadd-3133b30fb38c
		summarizeBy: none
		sourceColumn: nom_client

	column 'Numéro prêt'
		dataType: string
		lineageTag: 862bff5f-3c3f-40a4-8ecf-f51b7870da48
		summarizeBy: none
		sourceColumn: numero_pret

	column 'Montant initial'
		dataType: double
		lineageTag: 16a68dc0-1bf3-4ff8-a7f5-de9f017c18d9
		summarizeBy: none
		sourceColumn: montant_initial

	column Encours
		dataType: double
		lineageTag: 93d8b029-839b-4ac2-9b71-4fc1544af883
		summarizeBy: none
		sourceColumn: mtt_encours

	column 'Jours retard'
		dataType: int64
		lineageTag: c981d2b1-8983-4424-9fee-0b7b14ca9139
		summarizeBy: none
		sourceColumn: jours_retard

	column Arriéré
		dataType: double
		lineageTag: 1872b47e-5edb-4ca3-afde-73ab6c1597e7
		summarizeBy: none
		sourceColumn: montant_arriere

	column Provision
		dataType: double
		lineageTag: 3224d1ca-8f88-40c6-84bd-f0b0b3844db2
		summarizeBy: none
		sourceColumn: mtt_provision

	column 'PAR 1-30'
		dataType: double
		lineageTag: 361e7354-b42a-4221-af9d-9846efc585f4
		summarizeBy: none
		sourceColumn: par_1_30

	column 'PAR 31-60'
		dataType: double
		lineageTag: 0ff7b522-aab8-4391-adf2-d8c2e6532ac1
		summarizeBy: none
		sourceColumn: par_31_60

	column 'PAR 61-90'
		dataType: double
		lineageTag: 462a4934-2438-431a-8f7f-17e647f4b5aa
		summarizeBy: none
		sourceColumn: par_61_90

	column 'PAR 91-180'
		dataType: double
		lineageTag: 8e1c0a9e-bd1e-4ff0-a150-fa83d8b76dcf
		summarizeBy: none
		sourceColumn: par_91_180

	column 'PAR 180+'
		dataType: double
		lineageTag: dff68847-131a-4cea-a27e-9c14450189ea
		summarizeBy: none
		sourceColumn: par_180_plus

	column 'PAR 30+'
		dataType: double
		lineageTag: 28d0c5d2-13cf-4650-98d8-e531e8a2ad76
		summarizeBy: none
		sourceColumn: par_30_plus

	column 'PAR 90+'
		dataType: double
		lineageTag: f97f2533-0b1c-4bc5-a736-c54a8e6e24b8
		summarizeBy: none
		sourceColumn: par_90_plus

	column num_manuel
		dataType: string
		lineageTag: dd4e53a2-38ba-46ba-85b5-cef88c7767ec
		summarizeBy: none
		sourceColumn: num_manuel

		annotation SummarizationSetBy = Automatic

	column prenoms_client
		dataType: string
		lineageTag: 3aa191dc-7534-415c-a4c6-92517ad045f1
		summarizeBy: none
		sourceColumn: prenoms_client

		annotation SummarizationSetBy = Automatic

	column code_type_client
		dataType: int64
		formatString: 0
		lineageTag: 1454aec6-66df-44bd-8b58-aeafa634d887
		summarizeBy: sum
		sourceColumn: code_type_client

		annotation SummarizationSetBy = Automatic

	column type_client
		dataType: string
		lineageTag: a1549496-7f50-46cd-a730-50b45a9d5919
		summarizeBy: none
		sourceColumn: type_client

		annotation SummarizationSetBy = Automatic

	column numero_contrat
		dataType: string
		lineageTag: 8b3937b5-d9a3-433c-9726-5ad3b9ab9ac1
		summarizeBy: none
		sourceColumn: numero_contrat

		annotation SummarizationSetBy = Automatic

	column date_effet
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6cdaf95-25ae-4275-a3cd-d7be88009271
		summarizeBy: none
		sourceColumn: date_effet

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_decaissement
		dataType: dateTime
		formatString: Long Date
		lineageTag: c64f8c68-bb56-44fa-aa2d-e5b3edbe3854
		summarizeBy: none
		sourceColumn: date_decaissement

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_fin_echeance
		dataType: dateTime
		formatString: Long Date
		lineageTag: f588b5f7-e143-4172-8bfb-7aee367e45bb
		summarizeBy: none
		sourceColumn: date_fin_echeance

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column current_encours
		dataType: double
		lineageTag: df0d236d-d5cb-454f-b178-492bb86584e1
		summarizeBy: sum
		sourceColumn: current_encours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_Credit_PAR_Detail = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_par_detail"]}[Data],
					FiltreSituation = Table.SelectRows(TableSource, each [date_situation] = pDateFin),
					ColonnesModele = Table.SelectColumns(FiltreSituation, {
						"date_situation", "code_agence", "agence", "produit_credit", "devise",
						"code_client", "nom_client", "numero_pret", "montant_initial", "encours",
						"jours_retard", "arriere", "provision", "par_1_30", "par_31_60",
						"par_61_90", "par_91_180", "par_180_plus", "par_30_plus", "par_90_plus",
						"num_manuel", "prenoms_client", "code_type_client", "type_client", "numero_contrat",
						"date_effet", "date_decaissement", "date_fin_echeance", "current_encours"
					}),
					TypesModele = Table.TransformColumnTypes(ColonnesModele, {{"code_type_client", Int64.Type}}),
					Resultat = Table.RenameColumns(TypesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"encours", "mtt_encours"},
						{"arriere", "montant_arriere"},
						{"provision", "mtt_provision"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 96

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_par_detail

