/// Échéances de crédit futures regroupées par mois, produit et devise.
table F_Credit_Echeances_Futures
	lineageTag: 7847ef1b-2f13-4720-ae77-d5074601e680

	column 'Mois échéance'
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa501cee-0097-41a2-b267-af46b2ea0f15
		summarizeBy: none
		sourceColumn: mois_echeance

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: 2d2126ec-64cc-4f52-a340-eb1be81ca3ad
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: f6697ef4-a16b-4eac-b83e-1f88e4cb6e89
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: 60759d66-434a-45d4-a4a5-2081d631064a
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 3f950690-54cd-4a96-9ed7-6bacf357e28d
		summarizeBy: none
		sourceColumn: code_devise

	column 'Prêts concernés'
		dataType: int64
		lineageTag: bfb4f9c7-fa6c-4645-8b26-507f896140f4
		summarizeBy: none
		sourceColumn: nb_prets_concernes

	column Échéances
		dataType: int64
		lineageTag: d4ac3195-6169-4e73-b804-90194a6bc657
		summarizeBy: none
		sourceColumn: nb_echeances

	column 'Capital attendu'
		dataType: double
		lineageTag: 5eae0c64-8921-4ebb-aef7-c68e614012ce
		summarizeBy: none
		sourceColumn: capital_attendu

	column 'Intérêt attendu'
		dataType: double
		lineageTag: d3464a00-0b48-4cc0-93fb-03e883338570
		summarizeBy: none
		sourceColumn: interet_attendu

	column 'Commission attendue'
		dataType: double
		lineageTag: b86c85c9-be2e-4364-8bd1-951b37e88d56
		summarizeBy: none
		sourceColumn: commission_attendue

	column 'Épargne attendue'
		dataType: double
		lineageTag: 1b1b4891-28f3-4dbd-94b5-98768f3a0c6d
		summarizeBy: none
		sourceColumn: epargne_attendue

	column 'Total attendu'
		dataType: double
		lineageTag: 119c9db7-8a2a-45a0-96d9-cb75d724eacf
		summarizeBy: none
		sourceColumn: total_attendu

	partition F_Credit_Echeances_Futures = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_echeances_futures"]}[Data],
					MoisDebut = Date.StartOfMonth(Date.AddDays(pDateFin, 1)),
					MoisFin = Date.StartOfMonth(Date.AddYears(pDateFin, 1)),
					FiltrePeriode = Table.SelectRows(TableSource, each [mois_echeance] >= MoisDebut and [mois_echeance] <= MoisFin),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {
						"mois_echeance", "code_agence", "agence", "produit_credit", "devise",
						"prets_concernes", "echeances", "capital_attendu", "interet_attendu",
						"commission_attendue", "epargne_attendue", "total_attendu"
					}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"prets_concernes", "nb_prets_concernes"},
						{"echeances", "nb_echeances"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 100

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_echeances_futures

