/// Concentration du portefeuille sur les dix pour cent de prêts les plus importants.
table F_Credit_Concentration
	lineageTag: 36261360-aec8-4040-9d13-42dd2f13be9f

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20b8a9b9-3fc1-4903-8b9c-63fb555a0a65
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: 0a4ae123-2720-406c-a6e3-c3a26f2f8a9c
		summarizeBy: none
		sourceColumn: code_agence_demande

	column Agence
		dataType: string
		lineageTag: 3df2451c-7e5d-412a-8f96-a4f6866e57aa
		summarizeBy: none
		sourceColumn: nom_agence_demande

	column 'Produit crédit'
		dataType: string
		lineageTag: 45a24dc9-36ee-4cdb-a74f-d42013890c23
		summarizeBy: none
		sourceColumn: produit

	column Devise
		dataType: string
		lineageTag: 02430f24-dc1f-4961-83e4-d06da71b83cd
		summarizeBy: none
		sourceColumn: code_devise

	column 'Prêts actifs'
		dataType: int64
		lineageTag: 5cb13d1a-b764-4749-95b0-9bce0cc22602
		summarizeBy: none
		sourceColumn: nb_prets_actifs

	column Encours
		dataType: double
		lineageTag: 81c55697-4677-4f9b-92fb-7a829209f80f
		summarizeBy: none
		sourceColumn: encours_total

	column 'Encours top 10%'
		dataType: double
		lineageTag: 03752733-64b6-4ae9-8c30-25730a3b7ed2
		summarizeBy: none
		sourceColumn: encours_top_10_pct

	column 'Prêts top 10%'
		dataType: int64
		lineageTag: 3118f87f-185c-4835-bba5-256a59f34d22
		summarizeBy: none
		sourceColumn: nb_prets_top_10_pct

	column 'Part top 10%'
		dataType: double
		lineageTag: f2d932d1-be62-405b-8178-9ca0d8d465f5
		summarizeBy: none
		sourceColumn: part_top_10_pct

	partition F_Credit_Concentration = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_credit_concentration"]}[Data],
					DateSituation = pDateFin,
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] = DateSituation),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {"date_situation", "code_agence", "agence", "produit_credit", "devise", "prets_actifs", "encours", "encours_top_10_pct", "prets_top_10_pct", "part_top_10_pct"}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_demande"},
						{"agence", "nom_agence_demande"},
						{"produit_credit", "produit"},
						{"devise", "code_devise"},
						{"prets_actifs", "nb_prets_actifs"},
						{"encours", "encours_total"},
						{"prets_top_10_pct", "nb_prets_top_10_pct"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 105

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_credit_concentration

