/// Soldes d'épargne et nombre de comptes par mois, agence, produit et devise.
table F_Epargne_Soldes
	lineageTag: 4779fc61-c5b2-44a0-ad1f-132808d1778e

	column 'Date situation'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ec07486-4f08-4d5a-ba43-04d5cc9048d6
		summarizeBy: none
		sourceColumn: date_situation

		annotation UnderlyingDateTimeDataType = Date

	column Mois
		dataType: dateTime
		formatString: Long Date
		lineageTag: f8d63486-20ba-4c02-80ba-25fb8a9d8b1a
		summarizeBy: none
		sourceColumn: mois

		annotation UnderlyingDateTimeDataType = Date

	column 'Code agence'
		dataType: string
		lineageTag: da1b51c9-e439-42da-b8b9-2d888c65ceee
		summarizeBy: none
		sourceColumn: code_agence_compte

	column Agence
		dataType: string
		lineageTag: 99476c46-5233-4e25-895a-21a8164f30c7
		summarizeBy: none
		sourceColumn: nom_agence_compte

	column 'Produit épargne'
		dataType: string
		lineageTag: 30057528-df53-44fb-9f3c-6053ecf70f45
		summarizeBy: none
		sourceColumn: produit_epargne

	column 'Type compte'
		dataType: string
		lineageTag: e4f63f4e-08ed-4d35-a6f7-5c1ed20ae767
		summarizeBy: none
		sourceColumn: type_compte_adherent

	column Devise
		dataType: string
		lineageTag: d4881c9d-db50-43b8-908c-126a14ba5b2e
		summarizeBy: none
		sourceColumn: code_devise

	column Comptes
		dataType: int64
		lineageTag: ad4e88cc-3f8b-4cdb-81e5-da499e135b6e
		summarizeBy: none
		sourceColumn: nb_comptes

	column Clients
		dataType: int64
		lineageTag: ab29177c-8395-4573-b9dd-eb447cf48021
		summarizeBy: none
		sourceColumn: nb_clients

	column 'Solde épargne'
		dataType: double
		lineageTag: 2410e4fe-c5ac-45ba-ada0-0a7d27640615
		summarizeBy: none
		sourceColumn: solde_epargne

	column 'Solde moyen compte'
		dataType: double
		lineageTag: 52dc5336-fcb1-46c2-8973-e5c3d1a5a437
		summarizeBy: none
		sourceColumn: solde_moyen_compte

	partition F_Epargne_Soldes = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_epargne_soldes"]}[Data],
					DateSituationDebut = Date.EndOfMonth(pDateDebut),
					DateSituationFin = Date.EndOfMonth(pDateFin),
					FiltrePeriode = Table.SelectRows(TableSource, each [date_situation] >= DateSituationDebut and [date_situation] <= DateSituationFin),
					ColonnesModele = Table.SelectColumns(FiltrePeriode, {
						"date_situation", "mois", "code_agence", "agence", "produit_epargne",
						"type_compte", "devise", "comptes", "clients", "solde_epargne", "solde_moyen_compte"
					}),
					Resultat = Table.RenameColumns(ColonnesModele, {
						{"code_agence", "code_agence_compte"},
						{"agence", "nom_agence_compte"},
						{"type_compte", "type_compte_adherent"},
						{"devise", "code_devise"},
						{"comptes", "nb_comptes"},
						{"clients", "nb_clients"}
					})
				in
					Resultat

	annotation RequetePerfectVision = 103

	annotation SourceLocale = BB_VISION_REPORTING

	annotation SourceReportingObject = rpt.f_epargne_soldes

