/// Socle analytique client-devise pour les statuts, comptes, crédits, intérêts et DAT.
table F_Clients
	lineageTag: d5160e74-b20f-40e0-b9d1-9f89302811ce

	column 'Date début'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c210d1a9-8e96-4b84-88b2-4b129ae95da0
		summarizeBy: none
		sourceColumn: date_debut

		annotation UnderlyingDateTimeDataType = Date

	column 'Date fin'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ffd912ea-5bb4-495e-898e-000e33b64a87
		summarizeBy: none
		sourceColumn: date_fin

		annotation UnderlyingDateTimeDataType = Date

	column 'Code client'
		dataType: string
		lineageTag: 700b197a-25f6-4bfa-80c4-7eff71962b4b
		summarizeBy: none
		sourceColumn: code_client

	column 'Nom client'
		dataType: string
		lineageTag: d2a362ff-932b-46ad-9e6c-6fdeddf5d1f7
		summarizeBy: none
		sourceColumn: nom_client

	column 'Type client'
		dataType: string
		lineageTag: b630aa21-c1a8-42af-9bb5-225582f6dd03
		summarizeBy: none
		sourceColumn: type_client

	column 'Code agence'
		dataType: string
		lineageTag: 78298dc2-c24c-402c-a7a6-243180228e70
		summarizeBy: none
		sourceColumn: code_agence

	column Agence
		dataType: string
		lineageTag: f9d3f7ec-5931-4222-8416-db9753bde51a
		summarizeBy: none
		sourceColumn: agence

	column 'Date adhésion'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7ffeb26a-141e-42b0-a442-ea0669b2bf37
		summarizeBy: none
		sourceColumn: date_adhesion

		annotation UnderlyingDateTimeDataType = Date

	column Devise
		dataType: string
		lineageTag: b0167f8f-6b6e-40f4-9e55-19f29264d49b
		summarizeBy: none
		sourceColumn: devise

	column 'Statut client'
		dataType: string
		lineageTag: 2f3d4203-1e31-43ff-9e1b-77ffc6665924
		summarizeBy: none
		sourceColumn: statut_client

	column 'Client actif'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5d87a527-69e2-41f9-aa9e-a382e4b6321d
		summarizeBy: none
		sourceColumn: client_actif

		annotation SummarizationSetBy = Automatic

	column Comptes
		dataType: int64
		lineageTag: f62fc5ea-3c1f-4a9a-addc-f6a0cd2001a5
		summarizeBy: none
		sourceColumn: nombre_comptes

	column 'Comptes ouverts'
		dataType: int64
		lineageTag: 0f4facae-3b91-4217-830a-408fa0f7e200
		summarizeBy: none
		sourceColumn: nombre_comptes_ouverts

	column 'Comptes clôturés'
		dataType: int64
		lineageTag: 5cb11b99-4727-450e-89cc-216565c23930
		summarizeBy: none
		sourceColumn: nombre_comptes_clotures

	column 'Comptes bloqués'
		dataType: int64
		lineageTag: d39fe6c0-d0bf-4663-a11c-f5c85df9280f
		summarizeBy: none
		sourceColumn: nombre_comptes_bloques

	column 'Comptes dormants'
		dataType: int64
		lineageTag: 2caeee85-6457-4db4-bd96-5482cfdb5518
		summarizeBy: none
		sourceColumn: nombre_comptes_dormants

	column 'Comptes inactifs'
		dataType: int64
		lineageTag: a1b03413-88d0-40a1-8675-94bb54d36c6c
		summarizeBy: none
		sourceColumn: nombre_comptes_inactifs

	column 'Dernière opération'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e901f5c2-d1d2-4dd2-a8c8-3724ffb67c8f
		summarizeBy: none
		sourceColumn: date_derniere_operation

		annotation UnderlyingDateTimeDataType = Date

	column 'Solde épargne'
		dataType: double
		lineageTag: 3f1515ce-8e38-4e22-9928-74f14093e5c0
		summarizeBy: none
		sourceColumn: solde_epargne

	column 'Crédits actifs'
		dataType: int64
		lineageTag: 344895c9-f47d-4ce2-84d2-42082ad3c0f2
		summarizeBy: none
		sourceColumn: nombre_credits_actifs

	column 'Crédits à rembourser'
		dataType: int64
		lineageTag: 475cbcfa-3cbe-4950-a672-6fb58f42a9e2
		summarizeBy: none
		sourceColumn: nombre_credits_a_rembourser

	column 'Échéances crédit'
		dataType: int64
		lineageTag: c09d4ebb-9138-4ba4-bc1f-96515271c705
		summarizeBy: none
		sourceColumn: nombre_echeances_credit

	column 'Capital crédit prévu'
		dataType: double
		lineageTag: b43d7b42-ed0f-4f64-a6a6-4ab386033e40
		summarizeBy: none
		sourceColumn: capital_credit_prevu

	column 'Intérêt crédit à rembourser'
		dataType: double
		lineageTag: 334580e0-4a80-4d20-97a0-5e8fdbfa42c4
		summarizeBy: none
		sourceColumn: interet_credit_a_rembourser

	column 'Commission crédit prévue'
		dataType: double
		lineageTag: 0a9fccb9-e4f2-4129-a02c-ce98ee2ea8b3
		summarizeBy: none
		sourceColumn: commission_credit_prevue

	column 'Épargne crédit prévue'
		dataType: double
		lineageTag: 14e3ec24-1828-4153-9931-d6adf0c12b81
		summarizeBy: none
		sourceColumn: epargne_credit_prevue

	column 'Montant crédit à rembourser'
		dataType: double
		lineageTag: 4d4fe55e-f005-49ea-9fad-8493b5f6eb65
		summarizeBy: none
		sourceColumn: montant_credit_a_rembourser

	column 'Montant crédit restant'
		dataType: double
		lineageTag: 2d0f140b-91d7-47dd-95a0-9c78220fa823
		summarizeBy: none
		sourceColumn: montant_credit_restant

	column 'Intérêt épargne crédité'
		dataType: double
		lineageTag: 64630d83-40e5-46c6-9841-341a62087689
		summarizeBy: none
		sourceColumn: interet_epargne_credite

	column 'DAT à échéance'
		dataType: int64
		lineageTag: 3c244d90-4c5b-47f1-b356-56a9b9c00dab
		summarizeBy: none
		sourceColumn: nombre_dat_echeance

	column 'Montant DAT à échéance'
		dataType: double
		lineageTag: 8e3fa8f5-50db-44ca-9636-c69db9bc72ef
		summarizeBy: none
		sourceColumn: montant_dat_echeance

	column 'Première échéance DAT'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c6a0bcd-4166-4977-a473-7ea017d217ba
		summarizeBy: none
		sourceColumn: premiere_echeance_dat

		annotation UnderlyingDateTimeDataType = Date

	column 'Dernière échéance DAT'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac5dc311-5253-4c5c-bb9f-e8ad0f7b338f
		summarizeBy: none
		sourceColumn: derniere_echeance_dat

		annotation UnderlyingDateTimeDataType = Date

	column 'Avec compte ouvert'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0f5de2d8-bb45-4e23-a983-548877d25aa9
		summarizeBy: none
		sourceColumn: client_avec_compte_ouvert

		annotation SummarizationSetBy = Automatic

	column 'Avec compte bloqué'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 67416b6b-2c4a-49c2-8fe9-65114f80c614
		summarizeBy: none
		sourceColumn: client_avec_compte_bloque

		annotation SummarizationSetBy = Automatic

	column 'Avec compte dormant'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8a3f3aec-f2b9-4147-98ef-4a7dfd6411e1
		summarizeBy: none
		sourceColumn: client_avec_compte_dormant

		annotation SummarizationSetBy = Automatic

	column 'Avec crédit à rembourser'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 723927dd-6723-4302-a89b-0605b2742357
		summarizeBy: none
		sourceColumn: client_avec_credit_a_rembourser

		annotation SummarizationSetBy = Automatic

	column 'Avec intérêt crédit à rembourser'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3e663d96-df06-4704-b19e-49eb3d47db69
		summarizeBy: none
		sourceColumn: client_avec_interet_credit_a_rembourser

		annotation SummarizationSetBy = Automatic

	column 'Bénéficiaire intérêt épargne'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 276ab7e3-edff-4143-adb1-fc340cdbbde0
		summarizeBy: none
		sourceColumn: client_beneficiaire_interet_epargne

		annotation SummarizationSetBy = Automatic

	column 'Avec DAT à échéance'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 15d03558-80e9-4a0e-a0db-12081f2d7952
		summarizeBy: none
		sourceColumn: client_avec_dat_a_echeance

		annotation SummarizationSetBy = Automatic

	partition F_Clients = m
		mode: import
		source =
				let
					Source = Sql.Database(pServeur, pBaseReporting, [CreateNavigationProperties=false, CommandTimeout=#duration(0, 0, 10, 0)]),
					TableSource = Source{[Schema="rpt", Item="f_clients"]}[Data],
					FiltrePeriode = Table.SelectRows(TableSource, each [date_debut] = pDateDebut and [date_fin] = pDateFin),
					ColonnesRenommees = Table.RenameColumns(FiltrePeriode, {{"comptes", "nombre_comptes"}, {"comptes_ouverts", "nombre_comptes_ouverts"}, {"comptes_clotures", "nombre_comptes_clotures"}, {"comptes_bloques", "nombre_comptes_bloques"}, {"comptes_dormants", "nombre_comptes_dormants"}, {"comptes_inactifs", "nombre_comptes_inactifs"}, {"derniere_operation", "date_derniere_operation"}, {"credits_actifs", "nombre_credits_actifs"}, {"credits_a_rembourser", "nombre_credits_a_rembourser"}, {"echeances_credit", "nombre_echeances_credit"}, {"dat_a_echeance", "nombre_dat_echeance"}, {"montant_dat_a_echeance", "montant_dat_echeance"}, {"avec_compte_ouvert", "client_avec_compte_ouvert"}, {"avec_compte_bloque", "client_avec_compte_bloque"}, {"avec_compte_dormant", "client_avec_compte_dormant"}, {"avec_credit_a_rembourser", "client_avec_credit_a_rembourser"}, {"avec_interet_credit_a_rembourser", "client_avec_interet_credit_a_rembourser"}, {"beneficiaire_interet_epargne", "client_beneficiaire_interet_epargne"}, {"avec_dat_a_echeance", "client_avec_dat_a_echeance"}}, MissingField.Ignore),
					Resultat = Table.SelectColumns(ColonnesRenommees, {"date_debut", "date_fin", "code_client", "nom_client", "type_client", "code_agence", "agence", "date_adhesion", "devise", "statut_client", "client_actif", "nombre_comptes", "nombre_comptes_ouverts", "nombre_comptes_clotures", "nombre_comptes_bloques", "nombre_comptes_dormants", "nombre_comptes_inactifs", "date_derniere_operation", "solde_epargne", "nombre_credits_actifs", "nombre_credits_a_rembourser", "nombre_echeances_credit", "capital_credit_prevu", "interet_credit_a_rembourser", "commission_credit_prevue", "epargne_credit_prevue", "montant_credit_a_rembourser", "montant_credit_restant", "interet_epargne_credite", "nombre_dat_echeance", "montant_dat_echeance", "premiere_echeance_dat", "derniere_echeance_dat", "client_avec_compte_ouvert", "client_avec_compte_bloque", "client_avec_compte_dormant", "client_avec_credit_a_rembourser", "client_avec_interet_credit_a_rembourser", "client_beneficiaire_interet_epargne", "client_avec_dat_a_echeance"}, MissingField.UseNull)
				in
					Resultat

	annotation RequetePerfectVision = 157

	annotation SourceLocale = BB_VISION_REPORTING.rpt navigation

